apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      run: nginx-service
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        run: nginx-service
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
