apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-service
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-service
  type: ClusterIP
status:
  loadBalancer: {}
