apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxsvc-cluster
  name: nginxsvc-cluster
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxsvc
  type: ClusterIP
status:
  loadBalancer: {}
