apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxsvc-node
  name: nginxsvc-node
spec:
  ports:
  - name: http
    port: 80
    nodePort: 32169
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxsvc
  type: NodePort
status:
  loadBalancer: {}
