
# Creates a parallel job that runs a sleep command for 60 seconds and then exits.
# Creates three (3) jobs to complete, two (2) of them will run in parallel.
apiVersion: batch/v1
kind: Job
metadata:
  name: job-parallel
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
    spec:
      containers:
      - image: busybox
        name: job-parallel
        command: ["sleep", "60"]
        resources: {}
      restartPolicy: Never
status: {}
