# Demo of persisten volume hostPath storage in Kubernetes
#  hostPath represents a directory on the host.
#  This is useful for single-node development and testing only! 
#  On-host storage is not supported in any way and WILL NOT WORK in a multi-node cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-path
  labels:
    type: local
    app: myapp
spec:
# storageClassName is used to define the type of storage. manual is used for hostPath.
  storageClassName: manual
  capacity:
    storage: 1Gi
# accessModes define how the volume can be accessed. ReadWriteOnce means it can be mounted as read-write by a single node.
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
