apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-web
  name: my-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web
  strategy: {}
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - image: docker.io/username/our-web-server:0.0.1
        name: our-web-server
        resources: {}
      imagePullSecrets:
      - name: dockercreds
status: {}